name: cohack-cicd

env:
  AZURE_LOCATION: westeurope

on:
  push:
    branches:
      - "main"
    paths:
      - 'src/**'
      - '.github/workflows/cohack-cicd.yml'
  workflow_dispatch:

permissions:
      id-token: write
      contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: dotnet build
        run: dotnet build src --configuration Release
      - name: dotnet publish
        run: dotnet publish src -c Release -o artifact
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: cohack-app
          path: artifact

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: cohack-app
          path: artifact
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - uses: azure/arm-deploy@v1
        id: deployStep
        with:
          scope: subscription
          template: infra/azure/main.bicep
          deploymentName: coHackDeployment${{github.run_number}}
          region: ${{ env.AZURE_LOCATION }}
          parameters: runNumber=${{github.run_number}}
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ steps.deployStep.outputs.appServiceName }}
          package: ./artifact
